from .categoria import categoria
from .inventario import inventory
from .carritoitems import Cartitem
from .products import products
from .tipoproducto import product_type
from .ventas import ventas
from .compras import Compras
from .carritocompras import Cart
from .type import Type
from .user import User