# Generated by Django 4.1.1 on 2022-09-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('idtype', models.CharField(max_length=300, verbose_name='ID Type')),
                ('idnumber', models.CharField(max_length=30, verbose_name='ID Number')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idCart', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45, verbose_name='Status')),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaActualizacion', models.DateTimeField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userIds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidadExistencia', models.IntegerField(default=0)),
                ('cantidadComprada', models.IntegerField(default=0)),
                ('cantidadvendida', models.IntegerField(default=0)),
                ('fechaCompraInicial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoProducto', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(max_length=30, verbose_name='User_role')),
                ('right', models.CharField(max_length=30, verbose_name='Right')),
                ('logs', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('idVentas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fechaVenta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('idproducts', models.AutoField(primary_key=True, serialize=False)),
                ('name_prod', models.CharField(max_length=90)),
                ('author', models.CharField(max_length=45)),
                ('editorial', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('type_prod', models.CharField(max_length=45)),
                ('num_page', models.BigIntegerField()),
                ('isbn', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=250)),
                ('rank', models.CharField(max_length=45)),
                ('formato', models.CharField(max_length=45)),
                ('presentation', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('visits', models.BigIntegerField()),
                ('description', models.CharField(max_length=250)),
                ('cantidadExistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='bookFaceApp.inventory')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_producto', to='bookFaceApp.product_type')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='bookFaceApp.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idProducts', to='bookFaceApp.products')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=30)),
                ('subCategoria', models.CharField(max_length=30)),
                ('idAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('idCarItem', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('fechacreacion', models.DateTimeField()),
                ('fechaactualizacion', models.DateTimeField()),
                ('carritocompras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItem', to='bookFaceApp.cart')),
            ],
        ),
    ]
