# Generated by Django 4.1.1 on 2022-09-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookFaceApp", "0002_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user",
            new_name="id",
        ),
    ]
